# cloudbuild.yaml (Versión Corregida y Segura)

steps:
# 1. Construir la imagen del contenedor
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID:$COMMIT_SHA', '.']

# 2. Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID:$COMMIT_SHA']

# 3. Desplegar en Cloud Run, inyectando los secretos de forma segura
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'jumpseller-notifier' # Nombre de tu servicio en Cloud Run
    - '--image=gcr.io/$PROJECT_ID:$COMMIT_SHA'
    - '--platform=managed'
    - '--region=us-central1' # ¡Asegúrate de que esta sea tu región!
    - '--allow-unauthenticated' # Necesario para que Jumpseller pueda llamar al webhook
    - '--quiet'
    # Inyecta los secretos como variables de entorno
    - '--update-secrets=JUMPSELLER_LOGIN=jumpseller_login:latest,JUMPSELLER_TOKEN=jumpseller_token:latest'

# Especificamos la imagen que construimos
images:
- 'gcr.io/$PROJECT_ID/jumpseller-notifier:$COMMIT_SHA'
