# cloudbuild.yaml

steps:
# 1. Construir la imagen del contenedor
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/jumpseller-notifier:$COMMIT_SHA', '.']

# 2. Subir la imagen del contenedor a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/jumpseller-notifier:$COMMIT_SHA']

# 3. Desplegar la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'jumpseller-notifier' # El nombre de tu servicio en Cloud Run.
    - '--image=gcr.io/$PROJECT_ID/jumpseller-notifier:$COMMIT_SHA'
    - '--platform=managed'
    - '--region=us-central1' # Asegúrate de que esta sea la región correcta.
    - '--allow-unauthenticated'
    - '--quiet' # Evita prompts interactivos durante el despliegue automático.
    
    # --- IMPORTANTE ---
    # He añadido tu token. Ahora solo necesitas reemplazar el login.
    - '--set-env-vars=JUMPSELLER_LOGIN=guillermo@saiperfumes.cl,JUMPSELLER_TOKEN=b25f1135a1e6e72c6a98267966c5fb0d'

# Especificamos la imagen que acabamos de construir para que esté disponible.
images:
- 'gcr.io/$PROJECT_ID/jumpseller-notifier:$COMMIT_SHA'
